name: "Flake check"

env:
  XDG_CONFIG_HOME: /etc/

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  check:
    # TODO: The x86 machine is too broken for this... and also means that the ARM checks wouldn't run!
    runs-on: nix-aarch64-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up cache
        run: attic cache info homelab-main

      - name: Run om ci
        run: om ci run --include-all-dependencies -- --show-trace --accept-flake-config | attic push homelab-main --stdin

      - name: Print errors from previous run
        if: failure()
        run: cat /tmp/*.toml
