#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

# TODO: Iterate over all monitors
if [[ $(hostname) == "hydrogen" ]]; then
  bspc monitor DVI-I-0 -d 1 2 3 4 5 6 7 8 9 10
  bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
  eww open bar-desktop-1 &
  eww open bar-desktop-2 &
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
  eww open bar-laptop &
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -a '*:*:Picture-in-Picture' state=floating sticky=on

feh --bg-fill ~/.config/bspwm/wallpaper.jpg
xsetroot -cursor_name left_ptr # fix cursor

# picom --experimental-backends --backend glx &
